export const EVENTS_CLEAR = 'EVENTS_CLEAR'
export const EVENT_DELETE = 'EVENT_DELETE'
export const EVENTS_FILTER = 'EVENTS_FILTER'
export const EVENT_FORM_DATA = 'EVENT_FORM_DATA'
export const EVENT_ADD = 'EVENT_ADD'

export const EVENTS_GET_START = 'EVENTS_GET_START';
export const EVENTS_GET_SUCCESS = 'EVENTS_GET_SUCCESS';
export const EVENTS_GET_ERROR = 'EVENTS_GET_ERROR';
