export const CLEAR_EVENTS = 'CLEAR_EVENTS'
export const DELETE_EVENT = 'DELETE_EVENT'
export const FILTER_EVENTS = 'FILTER_EVENTS'
export const FORM_DATA_EVENT = 'FORM_DATA_EVENT'
export const ADD_EVENT = 'ADD_EVENT'

export const EVENTS_GET_START = 'EVENTS_GET_START';
export const EVENTS_GET_SUCCESS = 'EVENTS_GET_SUCCESS';
export const EVENTS_GET_ERROR = 'EVENTS_GET_ERROR';

export const DETAILS_FIND = 'DETAILS_FIND';
export const DETAILS_GET_START = 'DETAILS_GET_START';
export const DETAILS_GET_SUCCESS = 'DETAILS_GET_SUCCESS';
export const DETAILS_GET_ERROR = 'DETAILS_GET_ERROR';
